ALTER TABLE ai_poster_requests
ADD COLUMN IF NOT EXISTS error_code TEXT,
ADD COLUMN IF NOT EXISTS error_message TEXT,
ADD COLUMN IF NOT EXISTS error_detail TEXT,
ADD COLUMN IF NOT EXISTS error_request_id TEXT,
ADD COLUMN IF NOT EXISTS error_provider TEXT,
ADD COLUMN IF NOT EXISTS failed_at TIMESTAMPTZ;
